# Generated by Django 5.0 on 2024-01-02 23:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown_app', '0002_alter_event_id_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='event_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='countdown_app.event'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
