# Generated by Django 5.0 on 2024-01-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown_app', '0003_alter_event_id_alter_guest_event_id_alter_guest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='event_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
