# Generated by Django 5.0 on 2024-01-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown_app', '0006_alter_guest_assist_confirm_alter_guest_confirm_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='confirm_code',
            field=models.IntegerField(default=908403, editable=False),
        ),
    ]
