# Generated by Django 5.0 on 2024-01-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown_app', '0007_alter_guest_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='confirm_code',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
